# Generated by Django 2.0.7 on 2018-11-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20181109_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
